zuul:
  routes:
    resource:
      url: http://localhost:8085
    resource2:
      url: http://localhost:8086
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9191/uaa/user
    client:
      accessTokenUri: http://localhost:9191/uaa/oauth/token
      userAuthorizationUri: http://localhost:9191/uaa/oauth/authorize
      clientId: web
      clientSecret: secret
      grant-type: authorization_code,refresh_token

logging:
  level:
    org.springframework.security: DEBUG